"""Add T+1 predictive features

Revision ID: 5f25e48dcb7c
Revises: 5fdb8b90b81e
Create Date: 2026-06-05 14:29:24.393355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f25e48dcb7c'
down_revision: Union[str, None] = '5fdb8b90b81e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technical_features', sa.Column('rsi_7', sa.Float(), nullable=True))
    op.add_column('technical_features', sa.Column('stoch_k', sa.Float(), nullable=True))
    op.add_column('technical_features', sa.Column('stoch_d', sa.Float(), nullable=True))
    op.add_column('technical_features', sa.Column('volume_sma_20', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technical_features', 'volume_sma_20')
    op.drop_column('technical_features', 'stoch_d')
    op.drop_column('technical_features', 'stoch_k')
    op.drop_column('technical_features', 'rsi_7')
    # ### end Alembic commands ###
