"""Initial migration

Revision ID: 5fdb8b90b81e
Revises: 
Create Date: 2026-06-05 11:19:19.302382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '5fdb8b90b81e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('yahoo_ticker', sa.String(length=15), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('sub_sector', sa.String(length=100), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('market_cap_category', sa.String(length=20), nullable=True),
    sa.Column('shares_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('index_membership', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=False)
    op.create_index(op.f('ix_stocks_yahoo_ticker'), 'stocks', ['yahoo_ticker'], unique=True)
    op.create_table('watchlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight_technical', sa.Float(), nullable=True),
    sa.Column('weight_fundamental', sa.Float(), nullable=True),
    sa.Column('weight_sentiment', sa.Float(), nullable=True),
    sa.Column('weight_risk', sa.Float(), nullable=True),
    sa.Column('weight_catalyst', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_ohlcv',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('foreign_buy', sa.Float(), nullable=True),
    sa.Column('foreign_sell', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    op.create_table('technical_features',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sma_5', sa.Float(), nullable=True),
    sa.Column('sma_20', sa.Float(), nullable=True),
    sa.Column('sma_50', sa.Float(), nullable=True),
    sa.Column('sma_200', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_histogram', sa.Float(), nullable=True),
    sa.Column('bb_upper', sa.Float(), nullable=True),
    sa.Column('bb_middle', sa.Float(), nullable=True),
    sa.Column('bb_lower', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('adx_14', sa.Float(), nullable=True),
    sa.Column('obv', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    op.create_table('watchlist_items',
    sa.Column('watchlist_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('watchlist_id', 'ticker')
    )
    op.create_table('watchlist_scores',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('score_date', sa.DateTime(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('fundamental_score', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('catalyst_score', sa.Float(), nullable=True),
    sa.Column('classification', sa.String(length=20), nullable=True),
    sa.Column('score_details', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.PrimaryKeyConstraint('ticker', 'score_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_scores')
    op.drop_table('watchlist_items')
    op.drop_table('technical_features')
    op.drop_table('daily_ohlcv')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_stocks_yahoo_ticker'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
